### PR TITLE
Better using foreach reference.

### PR DESCRIPTION
**Pull request by Geolim4**
The title say it all :)

### CODE REVIEW

**Comment by shadowhand** [comment]
Better how?

**Comment by Geolim4** [comment]
Using the reference is more appropriated than accessing to the array using the key.

**Comment by shadowhand** [comment]
It's actually not.

**Comment by Geolim4** [comment]
Why ? The main purpose of foreach references is to avoid the syntax you doing, this is actually pretty the same thing :/

**Comment by shadowhand** [comment]
1. It is less commonly used, and therefore more likely to be misunderstood.
2. It is not significantly faster.

Which leads me to conclude there is no actual benefit.

**Comment by Geolim4** [comment]
1. If it less commonly used, that's because people are accustomed with old/bad practice. Giving the example will teach to the people the new/good ways :)
2. I agree, on a single call nope, you're right. Try with 10000 calls (or even more). As your function may be called many times for parsing purpose for example the difference can be significant.

**Comment by shadowhand** [comment]
1. I don't agree that it is bad practice. References increase cognitive load, which is the single biggest waste of time when programming. References are also more likely to have unintended side effects.
2. The key word is "significantly". The difference between 120ms and 110ms is not significant. (Numbers completely made up.) The burden of proof on performance is up to you.

**Comment by Geolim4** [comment]
1. I don't think we can talk about cognitive load in a context of a 17 lines function, i would agree if we were in a context of nested loop, but it's not. I didn't say directly that's a bad practice, but more something like a bad habit. It's a bit like using php4 constructors in PHP5 and saying "those constructors are still working, why do in other way" ?

2. The difference is pretty much, saying that "120ms or 110ms are not really different" is insane. I disagree, 10ms (in php especially) is something you can't just don't care about, and thinking  "The user will not see the difference". It's "bad", i'm talking about code optimization, yes the user will not see the difference just for this. But if we can save 10ms here, 15ms over there, 10 ms out there, we can finally reduce significantly the timespend. It's not only about you, it's about a whole.

You get the point i'm trying to explain ? ;)

**Comment by shadowhand** [comment]
1. Cognitive load should _always_ be taken into consideration. I think using references without a clear reason to do so is a bad habit, exactly because it does increase cognitive load and can produce unexpected side effects. It is nothing like php4 vs php5 constructors.
2. In the context of 100,000 or 10,000 loops it really is not any different. If we were talking about micro-optimizing in an embedded real time system, it would be hugely significant. But the truth is, these tiny differences in runtime code within the context of an application that is most likely connected to a database and being used over HTTP it is statistically insignificant. Having worked for top 50 websites in the world, I can say that with absolute confidence. Developer time (cognitive load) is much more important. You will never squeeze another 1000 req/s or even 10 req/s out of an app by these kinds of micro-optimizations. And there still is no proof this is actually any faster. There is no debate here.

**Pull request closed without merging**
